project:
  type: manuscript
  output-dir: docs

manuscript:
  article: index.qmd
  code-links:
   - repo

repo-url: https://github.com/gbv/bartoc-vocabulary-software

resources:
  - kos-software.json
  - bartoc-logo.svg

format:
  html:
    highlight-style: kate
    notebook-links: false
    theme: custom.scss
    favicon: bartoc-icon.png 
    template-partials:
      - toc.html
    header-includes: |
      <link rel="canonical" href="https://bartoc.org/software"/>
      <link rel="shortcut icon" href="bartoc-icon.png" type="image/png" />
#  pdf: default
