project:
  type: manuscript
  output-dir: docs

manuscript:
  article: index.qmd
  code-links:
   - repo

repo-url: https://github.com/gbv/bartoc-vocabulary-software

resources:
  - kos-software.json
  - bartoc-logo.svg

doi: https://10.5281/zenodo.15672524

format:
  html:
    highlight-style: kate
    notebook-links: false
    theme: custom.scss
    favicon: bartoc-icon.png 
    template-partials:
      - toc.html
    header-includes: |
      <link rel="canonical" href="https://bartoc.org/software"/>
      <link rel="shortcut icon" href="bartoc-icon.png" type="image/png" />
  pdf:
    notebook-links: false
    keep-tex: true
    classoption: DIV=10
    template-partials:
      - title.tex
    include-in-header: 
      text: |
        \usepackage[noblocks]{authblk}
        \renewcommand\Affilfont{\small}
        \usepackage{typearea}    
        \usepackage{floatrow}        
        \DeclareFloatFont{small}{\small}
        \floatsetup[table]{font=small}
